volumes:
  pocketbase-data: {}

services:
  pocketbase:
    image: pocketbase/pocketbase:edge
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      PB_ENCRYPTION_KEY: "ZWNhZTc0ZTI5YTZlZGZiMGJhZjdlNWE4"
    volumes:
      - pocketbase-data:/opt/pocketbase
